### ISSUE TITLE
optional indication on window focus if I click on the window

### ISSUE THREAD

**Issue by Alexmitter** [Leleat/focus-indicator-prototype#11]
It would be nice if that was possible. Just for the consistency of it. 

Thank you a lot for this experiment, I am very happy as a User with the current results.

**Comment by Leleat** [comment]
Sorry, I only develop this extension for GNOME's designers to test their ideas. (After they are done, I don't intend to maintain this extension. )

Please leave feedback and suggestions at https://discourse.gnome.org/t/window-focus-call-for-testing/13277/27 so they may consider it.
