### ISSUE TITLE
Non-active window may be risen when switching workplaces

### ISSUE THREAD

**Issue by leofontenelle** [Leleat/focus-indicator-prototype#7]
I'll attach a video. Depending on which app is the active one, when I come back to the working place a non-active app/window may be risen above another non-active app/window. The apps on the video are Firefox 108, GNOME settings 43 and GNOME Terminal 3.46.7, all of them installed from native packages on Arch Linux.
[Screencast_07_01_2023_21:06:16.webm](https://user-images.githubusercontent.com/2314430/211175307-5ece27f8-118f-4926-a94e-81cc1964fd95.webm)

**Comment by Leleat** [comment]
Pretty sure this is unrelated to my extension. I can reproduce this with my extension disabled and the session reloaded. Although it appears to need some specific windows? Here is a gif. Firefox is put below VS Code:

[scr.webm](https://user-images.githubusercontent.com/53054301/211205803-869ff37a-70b9-4208-a2cc-843ac3a6f6f8.webm)

Someone reported the same (or a similiar problem) here https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4704
