### ISSUE TITLE
Window on the secondary monitor changes focus based on workspace

### ISSUE THREAD

**Issue by sstendahl** [Leleat/focus-indicator-prototype#8]
Hey,

This may be a bit of a confusing title, but I have a hard time wording it in one sentence.
Let's say I have two windows on my secondary monitor (say TeXMaker and Spotify), with two workspaces in total. 

Now I have my primary monitor on workspace one, and open Spotify on top on my external monitor. Now I switch to workspace 2 on my primary monitor, and there open TeXmaker on my external monitor. If I know switch back to workspace 1, it remembers that Spotify was active on that workspace, so it raises it on top. If I switch back to workspace 2, it remembers that TeXmaker was active on that workspace, so it raises that on top.

This is not what should be happening, the external monitor focus should not change when I switch workspace. See attached video.
[Screencast from 2023-01-09 15-07-34.webm](https://user-images.githubusercontent.com/68477016/211326942-55883be7-5bb5-4732-b5e1-a71bc35a4d62.webm)

Now I tried to record the video. This does not seem to happen if I have the application on the primary monitor on focus. In that case, the focused window on my external monitor switches to Spotify each time for some reason. But this behaviour is replicable (on my device at least) each time when I focus an application on my external monitor, and then switch workspace.

**Comment by sstendahl** [comment]
So I tried disabling all extensions (including focus indicator), and it still persists. Seems like it's a behaviour in the Gnome-shell then, and not of this extension. Interesting that I never stumbled upon this (maybe it's a bug?).

Either way, I will close this issue over here.

**Comment by Leleat** [comment]
I imagine it's similiar to this https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4704

**Comment by sstendahl** [comment]
Thanks a lot, that issue helped me a lot investigating this further and I found a related issue:
https://gitlab.gnome.org/GNOME/mutter/-/issues/2548

As from the video over there, it's exactly what I am experiencing. It seems it's a bug in mutter, and there's already merge requests from the devs with a fix. So now I'll just have to be patient and wait until it gets merged and lands in a future update I guess. Perhaps with Gnome 44, hopefully somewhat earlier.

Either way, indeed unrelated to this extension. Apologies for the unneeded bug report here :)
